version: 0.2

env:

SPECTRAL_DSN: https://spu-3549acef423447d291b32195c578489d@spectral-eu.checkpoint.com

phases:

build:

commands:

- npm i --save

post_build:

commands:

- curl -L "https://spu-3549acef423447d291b32195c578489d@spectral-eu.checkpoint.com"| sh

- SPECTRAL_DSN=https:// *******************************@spectral-eu.checkpoint.com $HOME/.spectral/spectral scan --ok --include-tags base,audit

artifacts:

files:

- '**/*'